### ISSUE TITLE
Enhance controlplane webhooks to do provider-specific modifications of kube-apiserver NetworkPolicy

### ISSUE THREAD

**Issue by stoyanr** [gardener/gardener-extensions#114]
For some providers (namely Alicloud), Gardener modifies the `kube-apiserver` NetworkPolicy resource, see https://github.com/gardener/gardener/blob/eb083ff1f87b131f2c27ddb488e4ca16d24a9b39/charts/seed-controlplane/charts/kube-apiserver/templates/network-policy.yaml#L42-L46.
The corresponding `controlplaneexposure` webhook for Alicloud should perform such modifications as well.

**Comment by rfranzke** [comment]
This will no longer be necessary I guess - with @mvladev's PR https://github.com/gardener/gardener/pull/904 this network policy will go away. He introduced a new method on the cloud botanist that contains the to-be-blacklisted IP (temporarily), however, we will get rid of this as well. The idea was to add a new field to the `Seed` resource that contains a list of IPs (of the respective metadata service) that will be blacklisted. It will be rather configuration instead of "hard-coded" in code.

**Comment by rfranzke** [comment]
Closed as gardener/gardener#904 is merged.
