### ISSUE TITLE
Duplicate resources prevent the creation of a cluster

### ISSUE THREAD

**Issue by kramerul** [gardener/gardener-extensions#182]
**What happened**:

We are using gardener with an istio extension. During our [integration tests](https://concourse.istio.sapcloud.io/teams/garden/pipelines/gardener/jobs/integration-test), we create and delete a shoot cluster. We are always using the same cluster name. After a few loops we encountered the following error in the logs of a `<shoot>.infra.tf-job` 

```
Error: Error applying plan:

3 errors occurred:
        * aws_iam_role.nodes: 1 error occurred:
        * aws_iam_role.nodes: Error creating IAM Role shoot--core--integration-test-nodes: EntityAlreadyExists: Role with name shoot--core--integration-test-nodes already exists.
        status code: 409, request id: cd4798f1-9e59-11e9-9a03-27542a2f5747


        * aws_key_pair.kubernetes: 1 error occurred:
        * aws_key_pair.kubernetes: Error import KeyPair: InvalidKeyPair.Duplicate: The keypair 'shoot--core--integration-test-ssh-publickey' already exists.
        status code: 400, request id: d1b878e3-c75a-4fa6-82ab-8a50d11a2227


        * aws_iam_role.bastions: 1 error occurred:
        * aws_iam_role.bastions: Error creating IAM Role shoot--core--integration-test-bastions: EntityAlreadyExists: Role with name shoot--core--integration-test-bastions already exists.
        status code: 409, request id: cd4749f9-9e59-11e9-82f6-8f5e7da59408

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

**What you expected to happen**:

Duplicates should be either ignored or deleted.

**How to reproduce it (as minimally and precisely as possible)**:

Not sure how to reproduce this.

**Anything else we need to know?**:

**Environment**:

- Gardener version: master
- Kubernetes version (use `kubectl version`): 1.14.0
- Cloud provider or hardware configuration: AWS
- Others:

**Comment by kramerul** [comment]
We are able to reproduce this once a day.

**Comment by schrodit** [comment]
I saw similar behavior for route `0.0.0.0/0` in routetables that are already exist.
```
aws_route.private_utility_z0_nat: Error creating route: RouteAlreadyExists: The route identified by 0.0.0.0/0 already exists.
```

**Comment by ialidzhikov** [comment]
I hit the key pair issue on my local env. I suspect that the tf apply pod was started and reached some point and at the same time the hibernation schedule scaled down my seed nodes and the tf pod was evicted without being able to update the tf-state cm?

**Comment by schrodit** [comment]
We also suspect that this behavior should only happen if the tr pod is killed/evicted during its execution.
But on a running seed this seems very unlikely.

@Diaphteiros and me saw this behavior more often when running garden-setup and suspected that it happens if a seed needs to scale up..

**Comment by rfranzke** [comment]
NIce, thanks for digging into it @ialidzhikov. WDYT about switching from a `Job` to a `Pod`? We anyways use `backoffLimit=1` with somehow invalidates using a `Job`.

**Comment by ialidzhikov** [comment]
I guess this is the main reason for the duplicate infrastructures that we observed in the last days. On seed nodes scale down by the cluster-autoscaler or seed node eviction by machine-controller-manager for being unhealthy, this is very likely to happen.
The first `tf-job` is creating the infrastructure, the newly created one do creates again infra resource such as vpcs, etcd because the first pod hasn't updated the tfstate configmap yet. This results in duplicate infrastructure and at the end the new `tf-job` pod updates/overrides the state in a such manner that non-computed resources such as roles, instance profiles are missing and it will fail with conflicts as these resources are created by the first `tf-job` pod and the state for them is lost. And this results in failed Shoot creation.
We need to ensure that only 1 `tf-job`/`tf-apply` pod is acting at given moment. Your suggestion for switching to pod makes sense. I will try it.

**Comment by rfranzke** [comment]
Awesome, thanks @ialidzhikov, sounds very reasonable!
