### ISSUE TITLE
Duplicate KeyPair/Roles on AWS

### ISSUE THREAD

**Issue by Diaphteiros** [gardener/gardener-extensions#202]
**What happened**:
Shoot gets stuck during creation with the error message that a key pair and two roles (one with "nodes" and one with "bastion") belonging to the shoot are already present on the infrastructure and thus can't be created.
(Currently trying to reproduce the problem, will add exact error message afterwards)

**What you expected to happen**:
The shoot is created.

**How to reproduce it (as minimally and precisely as possible)**:
Not completely sure, but it seems that this happens when the seed needs to scale up during shoot creation.

**Anything else we need to know?**:
Has been observed for AWS shoots only. Seems to happen when the shoot is created, but the seed is full and during shoot creation, the auto-scaling of the seed cluster kicks in and scales up.
The error can be resolved by manually removing the duplicate key pair and roles from the infrastructure.

**Environment**:
- Gardener version: 0.26.2
- Cloud provider or hardware configuration: AWS

**Comment by rfranzke** [comment]
Please explain how to reproduce this. The provided explanation doesn't make much sense to me. The problem must somehow related to the fact that the Terraform job that creates the key pair and IAM roles is not able to save its state. Not sure why this may be caused by node scale-up.

Generally, if this situation happens, an administrator needs to look into it. We cannot automatically determine whether the duplicate key pair/roles can be removed without consequences (they might be used for other productive workloads and just have the same name "by accident"). The best we can do is to make sure that the state is saved after the resources have been created.

**Comment by kramerul** [comment]
Is this a duplicate of #182?

**Comment by Diaphteiros** [comment]
@kramerul Yes, it is. I didn't see that there is already an issue for that.

**Comment by Diaphteiros** [comment]
Closed because it is a duplicate of #182
