### ISSUE TITLE
Support additional HA concepts

### ISSUE THREAD

**Issue by MSSedusch** [gardener/gardener-extensions#220]
**What would you like to be added**:
Add support for additional HA concepts. For example, on Azure, Gardener only supports deploying VMs into Availability Sets.

In addition to AVSets, it would be great if Gardener and MCM could support these concepts as well:

* None  
  AVsets have some limitations e.g. on VMs that can be part of the same AVSet. In some cases it would be good to have a cluster without an HA concept
* Availability Zones  
  Availability Zones offer better VM SLAs (99.99 instead of 99.95 for AVSets)

**Why is this needed**:
More flexibility for customers and higher SLA

**Comment by vlerenc** [comment]
Could you please take a look at https://github.com/gardener/gardener-extensions/issues/135 and see whether we really need this ticket here @MSSedusch ?

What are the reasons for `None`? You wrote "AVsets have some limitations e.g. on VMs that can be part of the same AVSet", but I don't have the conext/know what limitations these are and why it would be good to support `None`?

cc @dkistner @AndreasBurger

**Comment by MSSedusch** [comment]
#135 only talks about supporting zones but I think having multiple HA concepts could be beneficial.

1. Availability Zones  
* + Offer highest VM SLA of 99.99% if you deploy two VMs across two zones
* + Allow to deploy VMs of different Hardware SKUs
* - only available in some regions
1. Availability Sets  
 * + available in all Azure regions
 * + offer higher SLA than single VM deployments
 * - only VM types that can run on the same hardware can be deployed into the same Availabiliy Set. For example, you cannot deploy a VM that supports GPUs with a VM that does not have GPUs which makes the support of worker pools less usefull.
1. None
 * + available in all Azure regions
 * + can support multiple hardware types e.g. VMs with GPU and VMs without GPU using worker pools
 * - lowest SLA of 99.9%

**Comment by vlerenc** [comment]
#135 is about availability zones. Yes, we have noticed that zones are not available everywhere. Your con argument with availability sets however seems not valid in our case: Since VMs in any worker pool are all based on the same VM type, you can't mix a GPU with a non-GPU machine. So by definition, the VMs of a worker pool all run on the same hardware, I assume? If that's right, then the pro argument for why we should add `None` is not (no longer) valid either, right? In that case, since we already support failure domains, I only see support for availability zones as a missing feature and that's what #135 is about.

In addition, so far nobody approached us with the wish to have no HA. It's not that by having `None`, end users would benefit in any way (costs?) and I cannot imagine anybody, if there is no penalty like that, to opt for no HA whatsoever. Can you?

**Comment by MSSedusch** [comment]
Closing this as duplicate of #135
