### ISSUE TITLE
Add an option for Flatcar Linux with OperatingSystemConfig

### ISSUE THREAD

**Issue by alban** [gardener/gardener-extensions#92]
Following up a discussion at KubeCon Barcelona:

Gardener now defines a resource of kind "OperatingSystemConfig" and it could be used to choose the alternative [Flatcar Linux](https://www.flatcar-linux.org/).

As far as I understand, the file [controllers/provider-aws/charts/provider-aws/values.yaml](https://github.com/gardener/gardener-extensions/blob/d9aef6c88ecf188d4d3c97dc65de9f59b79eea00/controllers/provider-aws/charts/provider-aws/values.yaml#L19) defines the AWS AMIs for "coreos". We could add an entry for "flatcar" here with its [4 channels](https://www.flatcar-linux.org/releases/): stable, beta, alpha, [edge](https://kinvolk.io/blog/2019/05/introducing-the-flatcar-linux-edge-channel/)

This was motivated by [Inspektor Gadget](https://github.com/kinvolk/inspektor-gadget) that currently works on the edge channel of Flatcar Linux.

This would also require to pass a [new parameter on the Kubelet command line](https://github.com/kinvolk/inspektor-gadget/blob/0e6c3fd71b4775c0e385ccd36afc08773a8ec594/Documentation/install.md#on-another-kubernetes-distribution) (`--cgroup-driver=systemd`) or [KubeletConfiguration](https://github.com/kinvolk/lokomotive-kubernetes/commit/22fb201c1e21034e5f5e81dd0f63d633be66370c#diff-97942f9b4a5f15c0b66ee126ef497e26R170) (`cgroupDriver: systemd`). But I am not sure where to specify that in the gardener extensions. Any pointers?

/cc @vasu1124

**Comment by vpnachev** [comment]
I have setup a garden cluster, where I have used FlatCars AMIs instead of the CoreOS ones.
The result is that the `os-coreos` is compatible with FlatCar(stable).

Thus I have opened a more general issue #318 which purpose is to make the current os controllers configurable. So that an ubuntu controller might act on `ubuntu` and `debian` at the same time, coreos controller might act on `coreos` and `flatcar` at the same time, and so on.
So we might close this issue in favor of #318?
